version: '3'

services:
  frontend:
    build: frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
    container_name: phones-front
    depends_on:
      - backend
  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports: 
      - 9000:9000